//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextPredict.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextPredict.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ants are social insects of the family Formicidae and , along with the related wasps and bees , belong to the order Hymenoptera . 
        ///Ants evolved from wasp-like ancestors in the mid-Cretaceous period between 110 and 130 million years ago and diversified after 
        ///the rise of flowering plants . More than 12 ,500 out of an estimated total of 22 ,000 species have been classified . They are easily identified by 
        ///their elbowed antennae and a distinctive node-like structure that forms a slender waist .
        ///
        ///Ants form  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ants {
            get {
                return ResourceManager.GetString("ants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bicycle is , in my opinion , is one of the best inventions in the world that has stood the test of time . It is a fun and speedy source of transportation , it provides valuable exercise and fresh air for your body , and the physical activity and speed of the ride helps to relax our often agitated mind .
        ///
        ///
        ///In many countries , the use of the bicycle was traditionally the primary source of transportation . As a country develops in economic wealth , the common bicycle tends to be replaced with the car .  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bicycle {
            get {
                return ResourceManager.GetString("bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of calories people should eat each day depends on several factors , including their age , size , height , sex , lifestyle , and overall general health . A physically active 6ft 2in male , aged 22 years , requires considerably more calories than a 5ft 2ins sedentary woman in her 70s .
        ///
        ///Recommended daily calorie intakes also vary across the world . According to the National Health Service ( NHS  ) , UK , the average male adult needs approximately 2 ,500 calories per day to keep his weight constan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string calories {
            get {
                return ResourceManager.GetString("calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiovascular diseases cause more than 15 million deaths in the world each year ,  according to the World Health Organization ( WHO; Geneva ) . 
        ///They account for 50% of all deaths in several developed countries ,  and more than 50% in Africa and Western and Southeast Asia . They are also 
        ///the major cause of death in adults . In addition ,  many cardiovascular incidents are not necessarily fatal ,  but may impair the ability to lead 
        ///a normal daily life ,  resulting in enormous healthcare costs ( estimat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Cardiovascular_disease {
            get {
                return ResourceManager.GetString("Cardiovascular_disease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball is a sport played by two teams of five players on a rectangular court . The objective is to shoot a ball through a hoop 18 inches 
        /// (  46 cm  ) in diameter and 10 feet  (  3 .0 m  ) high mounted to a backboard at each end . Basketball is one of the world&apos;s most popular and widely 
        ///viewed sports .
        ///A team can score a field goal by shooting the ball through the basket during regular play . A field goal scores two points for the shooting team if a player is touching or closer to the 
        ///basket than  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string how_to_play_basketball {
            get {
                return ResourceManager.GetString("how_to_play_basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve ever wondered about the basics of how to play American - style football , you&apos;re not alone  . 
        ///American football can seem confusing to the uninformed spectator  .
        ///Read on to learn how the game is played and what all those terms like “ first down ” and “ running back ” actually mean  .
        ///
        ///1  . Know the point of the game  . The goal of American football is to score points by carrying the ball from a starting point on a 100  -  yard 
        ///long by 53 - yard wide field into a specially marked ten - yard  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string how_to_play_fotbool {
            get {
                return ResourceManager.GetString("how_to_play_fotbool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The growth of plants toward light is particularly important at the beginning of their lifecycle . Many seeds germinate in the soil and get their nutrition in the dark from their limited reserves of starch and lipids . Reaching for the surface , the seedlings rapidly grow upwards against the gravitational pull , which provides an initial clue for orientation . With the help of highly sensitive light-sensing proteins , they find the shortest route to the sunlight -- and are even able to bend in the direction  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string science {
            get {
                return ResourceManager.GetString("science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a&apos;s
        ///able
        ///about
        ///above
        ///according
        ///accordingly
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///ain&apos;t
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///aren&apos;t
        ///around
        ///as
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///b
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words {
            get {
                return ResourceManager.GetString("stop_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello i am trying to write a few stop words.
        ///so if i will write simple words i will have more stop words.
        ///Let me write it all again..
        /// </summary>
        public static string stopWordsConversation {
            get {
                return ResourceManager.GetString("stopWordsConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term worm ( pronounced /?w?rm/ ) refers to an obsolete taxon ( vermes ) used by Carolus Linnaeus and Jean - Baptiste Lamarck for all 
        ///non - arthropod invertebrate animals , and stems from the Old English word wyrm . Currently it is used to describe many different distantly 
        ///related animals that typically have a long cylindrical tube - like body and no legs . Most animals called  &quot; worms &quot;  are invertebrates , but the 
        ///term is also used for the amphibian caecilians and the slow worm Anguis , a legless [rest of string was truncated]&quot;;.
        /// </summary>
        public static string worms {
            get {
                return ResourceManager.GetString("worms", resourceCulture);
            }
        }
    }
}
